config/routes.rb
Rails.application.routes.draw do
  devise_for :users, excepted: %i[registrations#edit]

  resources :searches, only: %i[index new create]
  resources :cars, only: %i[index]

  get '/help', to: 'static_pages#help'
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  validates :make, :model, :price, :year, :odometer, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates :year, numericality: { greater_than: 0 }
  validates :odometer, numericality: { greater_than: 0 }
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :searches, dependent: :destroy

  devise :database_authenticatable, :registerable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = CarsQuery.new.call(index_params)
  end

  private

  def index_params
    params.permit(:make, :model, :price_from, :price_to, :year_from, :year_to, :sort_type, :sort_direction, :page)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    authenticate_user!
    @searches = current_user.searches.order created_at: :desc
  end

  def new
    @search = Search.new
  end

  def create
    current_user&.searches&.create!(create_params)

    redirect_to cars_path(create_params)
  end

  private

  def create_params
    params.require(:search).permit(:make, :model, :price_from, :price_to, :year_from, :year_to)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def help; end

  def home; end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      if has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.haml
.container
  .row
    .col-3
      .h4.m-4
        = t('cars.index.choose_sort')
      %ul.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
        %li.nav-link.px-2
          = link_to t('cars.index.date_desc'), cars_path(request.params.merge(sort_type: :created_at).merge(sort_direction: :desc))
        %li.nav-link.px-2
          = link_to t('cars.index.date_asc'), cars_path(request.params.merge(sort_type: :created_at).merge(sort_direction: :asc))
        %li.nav-link.px-2
          = link_to t('cars.index.price_desc'), cars_path(request.params.merge(sort_type: :price).merge(sort_direction: :desc))
        %li.nav-link.px-2
          = link_to t('cars.index.price_asc'), cars_path(request.params.merge(sort_type: :price).merge(sort_direction: :asc))
    .col-4
      .h4.m-4
        = t('cars.index.cars_list')
      .h4.m-4
        = t('cars.index.cars_quantity', quantity: @cars.total_count)
      - @cars.each do |car|
        .col.m-4
          .card{style: "width: 25rem;"}
            .card-body  
              .card-text
                = t('cars.index.make', param: car.make)
              .card-text
                = t('cars.index.model', param: car.model)
              .card-text
                = t('cars.index.year', param: car.year)
              .card-text
                = t('cars.index.price', param: number_to_currency(car.price, unit: "$", format: "%n %u", delimiter: " "))
              .card-text
                = t('cars.index.odometer', param: car.odometer)
              .card-text
                = t('cars.index.description', param: car.description)
              .card-text
                = t('cars.index.make', param: car.created_at.to_date)
        .mb-3
      = paginate @cars
    .col-4
      -if params.key?(:make)
        .h4.m-4
          = t('cars.index.search_params')
        %ul.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
          %li.ml-2
            = t('cars.index.make', param: params[:make])
          %li.ml-2
            = t('cars.index.model', param: params[:model])
          %li.ml-2
            = t('cars.index.price_from', param: params[:price_from])
          %li.ml-2
            = t('cars.index.price_to', param: params[:price_to])
          %li.ml-2
            = t('cars.index.year_from', param: params[:year_from])
          %li.ml-2
            = t('cars.index.year_to', param: params[:year_to])

 

app/views/layouts/_header.html.haml
%header.p-3.bg-dark.text-white
  .container
    %nav.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
      %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
        %li= link_to 'Home', root_path, class: "nav-link px-2 text-white"
        %li= link_to 'Help', root_path, class: "nav-link px-2 text-white"
        %li= link_to 'Search', root_path, class: "nav-link px-2 text-white"
        %li= link_to 'Car List', cars_path, class: "nav-link px-2 text-white"
        %li= link_to 'My Searches', root_path, class: "nav-link px-2 text-white"
        %li= link_to 'Login', root_path, class: "nav-link px-2 text-white"
        %li= link_to 'Logout', root_path, class: "nav-link px-2 text-white"
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>CarAdverstimentsWeb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/searches/index.html.haml
.h4.m-5= t('searches.index.all_searches')

- @searches.each do |search|
  .col.m-4
    .card{style: "width: 25rem;"}
      .card-body  
        .card-text= t('searches.index.make', param: search.make)
        .card-text= t('searches.index.model', param: search.model)
        .card-text= t('searches.index.year_from', param: search.year_from)
        .card-text= t('searches.index.year_to', param: search.year_to)
        .card-text= t('searches.index.price_from', param: search.price_from)
        .card-text= t('searches.index.price_to', param: search.price_to)
        .card-text= t('searches.index.created_at', param: search.created_at.to_date) 
    .mb-3

app/views/searches/new.html.haml
.h1.m-4 New Search: 

= render 'shared/errors', object: @search

= form_with model: [@user, @search] do |f|
  .form-group.m-4
    .label.mb-2= f.label :make
    = f.text_field :make, placeholder: t('searches.new.placeholders.make')
  .form-group.m-4
    .label.mb-2= f.label :model
    = f.text_field :model, placeholder: t('searches.new.placeholders.model')
  .form-group.m-4
    .label.mb-2= f.label :year_from
    = f.text_field :year_from, placeholder: t('searches.new.placeholders.year_from')
  .form-group.m-4
    .label.mb-2= f.label :year_to
    = f.text_field :year_to, placeholder: t('searches.new.placeholders.year_to')
  .form-group.m-4
    .label.mb-2= f.label :price_from
    = f.text_field :price_from, placeholder: t('searches.new.placeholders.price_from')
  .form-group.m-4
    .label.mb-2= f.label :price_to
    = f.text_field :price_to, placeholder: t('searches.new.placeholders.price_to')
  .m-4= f.submit t('searches.new.placeholders.perform_search')

app/views/shared/_errors.html.haml
- if object.errors.full_messages.any?
  .alert.alert-danger 
    %ul.mb-0
      -object.errors.full_messages.each do |msg|
        %li
          = msg

app/views/shared/_flash.html.haml
- if notice 
  %p.alert.alert-success
    = notice
- if alert
  %p.alert.alert-danger
    = alert

app/views/shared/_header.html.haml
%header.p-3.bg-dark.text-white
  .container
    %nav.d-flex.flex-wrap.align-items-center.justify-content-center.justify-content-lg-start
      %ul.nav.col-12.col-lg-auto.me-lg-auto.mb-2.justify-content-center.mb-md-0
        %li
          = link_to t('static_pages.options.home'), root_path, class: "nav-link px-2 text-white btn btn-dark"
        %li
          = link_to t('static_pages.options.help'), help_path, class: "nav-link px-2 text-white btn btn-dark"
        %li
          = link_to t('static_pages.options.cars_list'), cars_path, class: "nav-link px-2 text-white btn btn-dark"
        %li
          = link_to t('static_pages.options.search'), new_search_path, class: "nav-link px-2 text-white btn btn-dark"
        %li
          = link_to t('static_pages.options.login'), new_user_session_path, class: "nav-link px-2 text-white btn btn-dark" if current_user.nil?
        %li
          = link_to t('static_pages.options.sign_up'), new_user_registration_path, class: "nav-link px-2 text-white btn btn-dark" if current_user.nil?
        %li
          = link_to t('static_pages.options.my_searches'), searches_path, class: "nav-link px-2 text-white btn btn-dark" if current_user
        %li
          = button_to t('static_pages.options.logout', user: current_user.email), destroy_user_session_path, method: :delete, class: "nav-link px-2 text-secondary btn btn-dark" if current_user
        

app/views/static_pages/help.html.haml
%h1 Help:
%table.table.table-striped.table-hover
  %thead
    %tr
      %th{:scope => "col"}
        = t('static_pages.help.description.option')
      %th{:scope => "col"}
        = t('static_pages.help.description.description')
  %tbody
    %tr
      %th{:scope => "row"}
        = t('static_pages.options.cars_list')
      %th{:scope => "row"}
        = t('static_pages.help.description.cars_list')
    %tr
      %th{:scope => "row"}
        = t('static_pages.options.help')
      %th{:scope => "row"}
        = t('static_pages.help.description.help')
    %tr
      %th{:scope => "row"}
        = t('static_pages.options.login')
      %th{:scope => "row"}
        = t('static_pages.help.description.login')
    %tr
      %th{:scope => "row"}
        = t('static_pages.options.logout_help')
      %th{:scope => "row"}
        = t('static_pages.help.description.logout')
    %tr
      %th{:scope => "row"}
        = t('static_pages.options.my_searches')
      %th{:scope => "row"}
        = t('static_pages.help.description.my_searches')
    %tr
      %th{:scope => "row"}
        = t('static_pages.options.search')
      %th{:scope => "row"}
        = t('static_pages.help.description.search')
    %tr
      %th{:scope => "row"}
        = t('static_pages.options.sign_up')
      %th{:scope => "row"}
        = t('static_pages.help.description.sign_up')
      

app/views/static_pages/home.html.haml
-if current_user.nil?
  .container-fluid
    %h4.m-4
      = "Welcome to 'Car Adverstiments Web!'"